name: demo_push

on:
  push: 
 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Build
        run: echo "Pipeline triggered successfully"

  need:
    runs-on: ubuntu-latest
    timeout-minutes: 0
    needs: build
    steps:
      - name: Build
        run: echo "Pipeline triggered successfully"
